Document: sneakers-demo
Title: Debian sneakers-demo Manual
Author: <insert document author here>
Abstract: This manual describes what sneakers-demo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sneakers-demo/sneakers-demo.sgml.gz

Format: postscript
Files: /usr/share/doc/sneakers-demo/sneakers-demo.ps.gz

Format: text
Files: /usr/share/doc/sneakers-demo/sneakers-demo.text.gz

Format: HTML
Index: /usr/share/doc/sneakers-demo/html/index.html
Files: /usr/share/doc/sneakers-demo/html/*.html
